apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
commonLabels:
  monokle: kustomize-demo
namespace: default
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-config.yaml
